services:
  - type: web
    name: tools-status-serverBasedAI
    env: docker
    repo: https://github.com/votre-nom/votre-repo
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: DISABLE_DNS_CHECKS
        value: true